name = "ai-chat-on-pages"
compatibility_date = "2024-04-01"
main = "functions/api/chat.js"

[vars]
MODEL = "google/gemini-2.5-flash-lite"
MAX_TOKENS = "2048"
SYSTEM_PROMPT = "You are a helpful assistant."
